import { Category } from "../types";

export const dummyCategories: Category[] = [  
  {    
    name:'Fusion',
    slug:'fusion',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Faucets',
    slug:'faucets',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Hoses and Connectors',
    slug:'hoses-and-connectors',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Buttons',
    slug:'buttons',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Shoes',
    slug:'shoes',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Furniture',
    slug:'furniture',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Valves',
    slug:'valves',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Siphons',
    slug:'siphons',
    description:'sgsdgfsdfsfds'
  },
]