import { Category } from "../types/types";

export const data: Category[] = [  
  {    
    name:'Accessories',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing1',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories234',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing789',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories70890',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing890',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories45',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing5675',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories2342',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing8676',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories787',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing123',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories235',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing6896',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories90',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing45677',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories7890',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing890',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
  {    
    name:'Accessories678',
    slug:'accessories',
    description:'sgsdgfsdfsfds'
  },
  {    
    name:'Clothing279',
    slug:'clothing',
    description:'sgsdgfdfgdsdfsfds'
  },
]